codecov:
  token: e59ef5c2-ed75-484b-9f9a-6b3c773c668b
  branch: master

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project: yes
    patch: yes
    changes: no

  ignore:
    - "tests/.*"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes